Azure/avdaccelerator

workload/portal-ui/portal-ui-baseline.json
Added filter for zonal support when selecting use availability zones. Fixed Vnet info dialog boxes - The old logic produced conflicting statements when selecting AAD identity and new VNET.
=> updated Baseline Portal UI

workload/arm/deploy-custom-image.json, workload/bicep/deploy-custom-image.bicep
Changed the compute gallery and image definition locations so they match the primary replication region for the image version. This is required so extra replication regions are not added to the image version automatically.
=> Changed computeGallery & imageDefinition location

workload/arm/deploy-baseline.json, workload/arm/deploy-custom-image.json, workload/bicep/avd-modules/avd-identity.bicep, workload/bicep/deploy-baseline.bicep, workload/bicep/parameters/deploy-baseline-parameters-example.json, workload/docs/deploy-baseline.md, workload/docs/getting-started-baseline.md, workload/portal-ui/portal-ui-baseline.json
- Removing parameter: createStartVmOnConnectCustomRole, no need to create this role anymore as it is part of built-in AVD roles now. 
- Removing from portal UI the field to get AVD (WVD) AAD ObjectID, now this is done via graph API call (thanks @jamasten for this contribution).
- Replacing custom roles with AVD built-in roles for start VM on connect and Scaling plans.
- Desktop Virtualization Power On Contributor (used to enable start VM on connect).
- Desktop Virtualization Power On Off Contributor (used to enable AVD scaling plans).
=> Role assignment updates

workload/portal-ui/brownfield/portalUiAutoIncreasePremiumFileShareQuota.json
Updated the resource scope in the UI definition for the Log Analytics Workspace and Automation Account resource types since those are the resources deployed in the solution.
Removed the location filter on the Resource Selector for the Storage Account resource in the UI definition since the storage account can be managed from any Azure location.
=> Fixed locations for Auto Increase Premium File Share Quota solution

workload/arm/brownfield/deployAlerts.json, workload/bicep/brownfield/alerts/deploy.bicep, workload/bicep/brownfield/alerts/modules/metricsResources.bicep, workload/bicep/brownfield/alerts/temp.json
@danycontre  - @jamasten  found an issue with the VM Metric Alerts and it was resolved in this update.  The HostPoolsInfo parameter was an object and not an array with objects.  Fixed the type in the BICEP and ARM templates.
=> JCore brownfield avd alerts

carml/1.3.0/Microsoft.Compute/diskEncryptionSets/deploy.bicep, workload/arm/deploy-baseline.json, workload/bicep/deploy-baseline.bicep, workload/bicep/modules/StorageAzureFiles/.bicep/managementVm.bicep, workload/bicep/modules/avdSessionHosts/.bicep/avdSessionHosts.bicep, workload/bicep/modules/avdSessionHosts/deploy.bicep, workload/portal-ui/portal-ui-baseline.json
Deployment:
- Added a policy definition, assignment, and remediation task to disable network access on any disks in the subscription
- Added a disk encryption set, key vault, and key to enable server-side encryption with double encryption (PMK and CMK)
- Enabled encryption at host to ensure temp and cache disks are encrypted
Portal UI: 
- Added a checkbox to enable zero trust
- Added inputs for custom resource names
=> Added Zero Trust configuration for AVD Session Host Disks

.github/workflows/psdocs-mdtogit.yml, workload/bicep/deploy-baseline.bicep, workload/bicep/deploy-custom-image.bicep, workload/bicep/generateddocs/deploy-baseline.bicep.md, workload/bicep/generateddocs/deploy-custom-image.bicep.md, workload/bicep/modules/Identity/deploy.bicep, workload/bicep/modules/avdInsightsMonitoring/.bicep/azurePolicyMonitoring.bicep, workload/bicep/modules/avdInsightsMonitoring/.bicep/monitoringEventsPerformanceCounters.bicep, workload/bicep/modules/avdInsightsMonitoring/deploy.bicep, workload/bicep/modules/avdManagementPlane/deploy.bicep, workload/bicep/modules/avdSessionHosts/.bicep/availabilitySets.bicep, workload/bicep/modules/avdSessionHosts/.bicep/avdSessionHosts.bicep, workload/bicep/modules/avdSessionHosts/.bicep/azurePolicyGpuExtensions.bicep, workload/bicep/modules/avdSessionHosts/.bicep/configureFslogixOnSessionHosts.bicep, workload/bicep/modules/avdSessionHosts/.bicep/registerSessionHostsOnHopstPool.bicep, workload/bicep/modules/avdSessionHosts/deploy.bicep, workload/bicep/modules/azurePolicyAssignmentRemediation/deploy.bicep, workload/bicep/modules/networking/.bicep/azurePolicyNetworkMonitoring.bicep, workload/bicep/modules/networking/.bicep/privateDnsZones.bicep, workload/bicep/modules/networking/deploy.bicep, workload/bicep/modules/postDeploymentTempResourcesCleanUp/deploy.bicep, workload/bicep/modules/storageAzureFiles/.bicep/AzureFilesDomainJoin.bicep, workload/bicep/modules/storageAzureFiles/.bicep/managementVm.bicep, workload/bicep/modules/storageAzureFiles/deploy.bicep, workload/bicep/modules/zeroTrust/.bicep/zeroTrustKeyVault.bicep, workload/bicep/modules/zeroTrust/deploy.bicep, workload/bicep/readme.md
This is a GitHub Workflow which is used in ALZ-Bicep which I have adjusted to run in AVD Accelerator to generate a markdown file for parameter details in the deployment baselines (both standard and custom image).
Changes:
- New workflow in GH Actions for documentation creation
- Creates a 'generateddocs' folder under 'bicep'
- Creates two Markdown files which are human readable for parameter details inside
- A link to both markdowns is in the README.md
- Amended all `@description` decorators to read as `@sys.description` to comply with Bicep best practices
- Added metadata for `name` and `description` for additional detail in the Markdown files
- The workflow triggers from PRs on the `deploy-baseline.bicep` file and the `deploy-custom-image.bicep` file *ONLY*
This needs multiple reviews …
=> Automatic Documentation Creation

workload/scripts/DSCStorageScripts/script-domainjoinstorage.ps1
This PR adds the best practice NTFS permissions to the storage account for FSLogix User Profiles
1. Added additional commands to run to apply permissions to the FSLogix File Share
1. N/A
TO BE DELIVERED
=> US 29605 - FSLogix Configuration-NTFS permissions 

carml/1.3.0/Microsoft.Network/virtualNetworks/deploy.bicep, workload/arm/deploy-baseline.json, workload/bicep/modules/networking/deploy.bicep
Allows the selecrion of a blank array for log categories on Virtual Network diagnostic settings because Azure US Gov does not support allLogs.
1. Virtual Netwok deployment to Azure US Government with monitoring selected.
1. None
Tested as part of my deployment to Azure US Gov and also submitted CARML PR. https://github.com/Azure/ResourceModules/pull/3448
- [ x] Read the [Contribution Guide](https://github.com/Azure/avdaccelerator/blob/main/CONTRIBUTING.md) and ensured this PR is compliant with the guide
- [ x] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [ x] Associated it with relevant [GitHub …
=> Fix azure us gov network diag settings

carml/1.3.0/Microsoft.Automation/automationAccounts/deploy.bicep, workload/arm/brownfield/deployAutoIncreasePremiumFileShareQuota.json
While deploying the Auto Increase File Share Quota solution / brownfield scenario in a LevelUp lab, I discovered new subscriptions do not support setting the retention policy on logs and metrics for diagnostic settings. After removing the retention policies on the diagnostic setting for the Automation Account, the solution deploys successfully and in working order.
=> Fixed diagnostic settings for Automation Account in CARML

carml/1.3.0/Microsoft.Storage/storageAccounts/deploy.bicep, carml/1.3.0/Microsoft.Storage/storageAccounts/readme.md, workload/arm/deploy-baseline.json, workload/bicep/modules/avdSessionHosts/deploy.bicep, workload/docs/baseline-troubleshooting-guide.md, workload/docs/citrixlzaccelerator/readme.md, workload/docs/deploy-baseline.md, workload/docs/horizonlzaccelerator-nextgen/readme.md, workload/docs/horizonlzaccelerator/readme.md, workload/portal-ui/portal-ui-baseline.json, workload/terraform/greenfield/AADDSscenario/output.tf, workload/terraform/greenfield/AADDSscenario/readme.md, workload/terraform/greenfield/AADDSscenario/variables.tf, workload/terraform/greenfield/AADscenario/output.tf, workload/terraform/greenfield/AADscenario/readme.md, workload/terraform/greenfield/AADscenario/variables.tf, workload/terraform/greenfield/ADDSscenario/output.tf, workload/terraform/greenfield/ADDSscenario/variables.tf, workload/terraform/greenfield/readme.md, workload/terraform/greenfield/zerotrust/output.tf, workload/terraform/greenfield/zerotrust/variables.tf, workload/terraform/modules/avd/personal/variables.tf
=> Replace AAD/ Add Microsoft Entra ID

workload/arm/deploy-baseline.json, workload/arm/deploy-custom-image.json, workload/bicep/modules/storageAzureFiles/.bicep/azureFilesDomainJoin.bicep
Wrap domain join password in `'` in the PowerShell command.
1. Fixes #515
=> Support `|` and other special characters in domain join password

workload/bicep/modules/storageAzureFiles/deploy.bicep
Enabling large files shares for standard storage accounts.
1. Enabling large files shares for standard storage accounts.
=> Enabling large files shares for standard storage accounts.

workload/arm/deploy-baseline.json, workload/arm/deploy-custom-image.json, workload/bicep/deploy-baseline.bicep, workload/bicep/deploy-custom-image.bicep, workload/bicep/parameters/deploy-custom-image-parameters-example.json, workload/docs/autoGenerated/deploy-baseline.bicep.md, workload/docs/autoGenerated/deploy-custom-image.bicep.md, workload/portal-ui/brownfield/portalUiAppAttachToolsVM.json, workload/portal-ui/portal-ui-baseline.json, workload/portal-ui/portal-ui-custom-image.json, workload/variables/osMarketPlaceImages.json
Adding 23H2 OS image option and fixing baseline portal UI bug
1. Adding 23H2 OS image option for baseline and custom image build. 
2. Fixing baseline portal UI bug, so AD domain name info is not requested when deploying FSLogix/App attach and using entra ID as identity service provider.
1. None
- [x ] Checked for duplicate [Pull …
=> Adding 23H2 OS image option and fixing baseline portal UI bug

workload/portal-ui/portal-ui-baseline.json
1. Fixes portal UI VM size selector to use session host location instead of management plane location.
1. None
=> VM Size Selector Region fix

workload/bicep/brownfield/appAttachToolsVM/solution.bicep
URGENT Fix: Brownfield for App Attach VM was not configuring the VM via post deployment script as it was using a URL for Github that was not the "Raw content" version thus the PS1 on the VM was an HTML download.  Adjusted the URL to correct the issue. This impacted all previous deployments since it was added to the accelerator.
1. Variable with Post Deployment URL now correct
N/A
Re-deployed from updated code via a Template Spec and script downloaded and executed successfully. Easily noted by script's output log and the configuration for the VM was correct with added App Attach Tools.
=> Brownfield - Urgent Fix for App Attach VM Deployment

workload/terraform/greenfield/AADDSscenario/avd.tf, workload/terraform/greenfield/AADscenario/avd.tf, workload/terraform/greenfield/ADDSscenario/avd.tf, workload/terraform/greenfield/zerotrust/avd.tf
There was a bug in the code that stopped the scaling plan from being created. It was caused by the role assignment not giving the correct role. This resulted in a permission error when creating the scaling plan. I solved the bug by changing the application_id to object_id, as the terraform documentation suggests.
1. I have fixed the error in the 4 scenarios in the greenfield folder
1. Fix the error in the role assignment using object_id instead of application_id
I have personally tested only the ADDS scenario, that make me confident the scaling plan creation is working as expected as a consequence of right role assignment fixed.
=> Scaling plan creation failing [fixed]

carml/1.3.0/Microsoft.Compute/virtualMachines/deploy.bicep, workload/arm/deploy-baseline.json, workload/bicep/deploy-baseline.bicep, workload/bicep/modules/avdSessionHosts/deploy.bicep, workload/bicep/modules/storageAzureFiles/.bicep/managementVm.bicep
1. Fixes issue 523 by allowing the disk size to be set to Null for automatically setting to size of provided image.
=> Issue 523 fix

carml/1.3.0/Microsoft.Compute/virtualMachines/deploy.bicep, workload/arm/deploy-baseline.json, workload/bicep/deploy-baseline.bicep, workload/bicep/modules/avdSessionHosts/deploy.bicep, workload/bicep/parameters/deploy-baseline-parameters-example.json
1. Adds option to customize OS disk size larger than image size
Deployments using custom size and without custom size deployed successfully.
=> Disksize update

workload/bicep/modules/zeroTrust/.bicep/zeroTrustKeyVault.bicep
In Azure Gov, the federatedClientId attribute on the disk encryption set is not available. Instead of setting that attribute to 'None' as the default value, this change removes any value for that attribute.
1. #512  In the Zero Trust module, adds the attribute federatedClientId and sets the value to blank.
N/A
=> Set federatedClientId to blank in ZT module

workload/arm/deploy-baseline.json, workload/bicep/deploy-baseline.bicep
The cm-resource-parent tag is not being populated with a valid resource ID - the subscription ID has as tailing }
1. Fixes cm-resource-parent in bicep
2. Fixes cm-resource-parent in ARM
1. Customers using the incorrect tag value would have to update reporting for future deployments
Bicep deployment:
=> remove tailing } from resource id in cm-resource-parent tag

workload/arm/brownfield/deployNewSessionHostsToHostPools.json, workload/bicep/brownfield/newSessionHosts/deploy.bicep, workload/portal-ui/brownfield/portalUiNewSessionHosts.json
1. Fixing new session host brownfield FSLogix setup bug.
1. None
=> New SH browfield FSLogix setup fix

workload/arm/deploy-baseline.json, workload/bicep/deploy-baseline.bicep
=> Switching KV auth to RBAC

avm/1.0.0/res/network/virtual-network/main.bicep, workload/arm/deploy-baseline.json, workload/arm/deploy-custom-image.json, workload/bicep/modules/networking/deploy.bicep
Closes #723 
1. Adds the word `Resource` in the property names of the network security group and route table resource ID properties that are passed to the AVM network module.
N/A
N/A
=> Fix property name mismatch to set NSG and RT on subnets

workload/portal-ui/portal-ui-baseline.json
=> Baseline portal UI clean-up

workload/arm/deploy-baseline.json, workload/bicep/deploy-baseline.bicep
1. Depends on logic fix
1. none
=> Bug 812 fix
