Azure/avdaccelerator

Terraform/.gitattributes
Terraform/.github/workflows/documentation.yml
Terraform/.gitignore
Terraform/.vscode/settings.json
Terraform/LICENSE
Terraform/README.md
Terraform/USAGE.md
Terraform/main.tf
Terraform/modules/SIG/main.tf
Terraform/modules/SIG/variables.tf
Terraform/modules/avd/main.tf
Terraform/modules/avd/networking.tf
Terraform/modules/avd/random.tf
Terraform/modules/avd/rbac.tf
Terraform/modules/avd/variables.tf
Terraform/modules/log-analytics/main.tf
Terraform/modules/log-analytics/random.tf
Terraform/modules/log-analytics/variables.tf
Terraform/modules/storage/main.tf
Terraform/modules/storage/random.tf
Terraform/modules/storage/variables.tf
Terraform/prereq/backendsetup.md
Terraform/provider.tf
Terraform/terraform.tfvars.example
Terraform/variables.tf

Add terraform folder and modules

add terraform

---

README.md

Does this look good? Added description in getting Started.md as well to clarify this is for first build (starter kit) not ongoing.

Added description to buttons

---

workload/portal-ui/portal-ui-baseline.json

UI update to ask for domain join account password confirmation

---

workload/arm/deploy-baseline.json
workload/deploy-baseline.bicep

Add sleep timer after fslogix mi is created

---

workload/bicep/deploy-baseline.bicep

Added telemetry enablement bool, variable for UUID, and telemetry deployment.
@danycontre @nataliakon @xelizondo please review

add telemetry

---

workload/terraform/avdbaseline/afstorage.tf
workload/terraform/avdbaseline/host.tf
workload/terraform/avdbaseline/main.tf
workload/terraform/avdbaseline/networking.tf
workload/terraform/avdbaseline/nsg.tf
workload/terraform/avdbaseline/routetable.tf
workload/terraform/avdbaseline/terraform.tfvars.sample
workload/terraform/avdbaseline/variables.tf

Fix issue and updated variables and host files

issues fix and updates

---

workload/terraform/readme.md

Note to deploy custom image build before baseline

Terraform readme update 

---

workload/bicep/readme.md

Baseline and image were twisted

Wrong Headline

---

workload/arm/deploy-baseline.json
workload/bicep/avd-modules/avd-storage-azurefiles.bicep
workload/vm-custom-extensions/add-azure-files-to-domain-script.bicep

Merging @nataliakon work on securing input values for domain join

Script bug

---

readme.md
workload/terraform/greenfield/avdbaseline/network/readme.md
workload/terraform/greenfield/avdbaseline/readme.md

Update links on readme for images

Terraform readme links update

---

workload/arm/deploy-baseline.json
workload/bicep/avd-modules/avd-storage-azurefiles.bicep

Adding delay to the fslogix setup deployment, so we give time for the management VM to be online and ready for extension deployment

Delay introduction

---

workload/arm/deploy-baseline.json
workload/bicep/avd-modules/avd-identity.bicep

Movin scaling plan role assignment from subscription to deployment compute and service objects RG level, this will avoid multi deployment on the same subscription errors.

Scaling plan IAM role assignment fix

---

.azuredevops/ado/main-ado-avd-accelerator.yml

Cleaned up the parameters.

---

carml/1.2.0/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface.bicep
workload/arm/deploy-baseline.json
workload/bicep/avd-modules/avd-session-hosts.bicep
workload/bicep/avd-modules/avd-storage-azurefiles.bicep

Fix ASG VM membership issue

---

workload/docs/deploy-baseline.md
workload/docs/deploy-custom-image.md
workload/docs/getting-started.md
workload/docs/resource-naming.md

Addresses markdown issues highlighted in #212 
Update ensures tables are formatted correctly, but also addresses issues in markdown, spelling, grammar and improves some formatting
* Fixes markdown linting issues including table formatting issues, headings, spelling and grammar
* Fix additional markdown linting issues and table formatting problems
* Align deployment tables across documents; Update table formatting

Address docs markdown issues

---

workload/bicep/avd-modules/avd-session-hosts.bicep
workload/bicep/avd-modules/avd-storage-azurefiles.bicep
workload/bicep/deploy-baseline.bicep

Merge test

---

workload/arm/deploy-baseline.json
workload/terraform/greenfield/avdbaseline/provider.tf

Add partner id

---

workload/portal-ui/portal-ui-baseline.json

Custom regex removed and custom error message removed, now using standard function for local admin password

Removed regex and custom message

---

workload/bicep/deploy-baseline.bicep
workload/portal-ui/portal-ui-baseline.json

Added cm-resource-parent tag to be added to resources by default and group resource costs under the host pool resource for cost visibility

Added cm-resource-parent tag

---

workload/bicep/deploy-custom-image.bicep
workload/scripts/Optimize_OS_for_AVD.ps1

a few typos in comments and other places. No real change to code.

Fixed some typos

---

workload/terraform/greenfield/AADscenario/afstorage.tf
workload/terraform/greenfield/AADscenario/data.tf
workload/terraform/greenfield/AADscenario/host.tf
workload/terraform/greenfield/AADscenario/keyvault.tf
workload/terraform/greenfield/AADscenario/locals.tf
workload/terraform/greenfield/AADscenario/main.tf
workload/terraform/greenfield/AADscenario/provider.tf
workload/terraform/greenfield/AADscenario/rg.tf
workload/terraform/greenfield/AADscenario/variables.tf
workload/terraform/greenfield/ADDSscenario/afstorage.tf
workload/terraform/greenfield/ADDSscenario/data.tf
workload/terraform/greenfield/ADDSscenario/host.tf
workload/terraform/greenfield/ADDSscenario/keyvault.tf
workload/terraform/greenfield/ADDSscenario/locals.tf
workload/terraform/modules/insights/avdi.tf
workload/terraform/modules/keyvault/keyvault.tf
workload/terraform/modules/keyvault/locals.tf
workload/terraform/modules/network/firewallrules/fwpolicy.tf

Modify DNS zone for private endpoints to use private dns zones in the hub 
Link private endpoints to DNS and enable

Terraform dnslink

---

carml/1.2.0/Microsoft.DesktopVirtualization/hostpools/deploy.bicep
carml/1.2.0/Microsoft.DesktopVirtualization/hostpools/readme.md
workload/bicep/avd-modules/avd-management-plane.bicep

And add output variable to docs

Correct output variable name

---

workload/terraform/greenfield/AADscenario/terraform.tfvars.sample
workload/terraform/greenfield/ADDSscenario/keyvault.tf
workload/terraform/greenfield/readme.md
workload/terraform/modules/keyvault/keyvault.tf
workload/terraform/modules/keyvault/locals.tf
workload/terraform/modules/network/networking.tf
workload/terraform/modules/network/nsg.tf

Update to readme file to fix getting started link.
Update to sample tfvars include recent versions and variables.

readme and samples file update

---

workload/docs/deploy-baseline.md
workload/docs/getting-started-baseline.md
workload/portal-ui/portal-ui-baseline.json

Added support for Azure US Government and fixed session host region selection logic.

Baseline portal UI update

---

workload/terraform/greenfield/AADscenario/main.tf
workload/terraform/greenfield/ADDSscenario/main.tf
workload/terraform/modules/network/firewallrules/fwpolicy.tf
workload/terraform/modules/network/firewallrules/variables.tf

update variables and add option to main that can be uncommented for use

update fw policy

---

workload/bicep/deploy-baseline.bicep

verified and tested in Azure Government with AADDS identity type. follows similar convention to custom image deployment.

changed hardcode parameter for AzureCloudEnvironment to dynamic environment name

---

workload/terraform/greenfield/AADscenario/afstorage.tf
workload/terraform/greenfield/AADscenario/avd.tf
workload/terraform/greenfield/AADscenario/data.tf
workload/terraform/greenfield/AADscenario/keyvault.tf
workload/terraform/greenfield/AADscenario/main.tf
workload/terraform/greenfield/AADscenario/provider.tf
workload/terraform/greenfield/AADscenario/terraform.tfvars.sample
workload/terraform/greenfield/AADscenario/variables.tf
workload/terraform/greenfield/ADDSscenario/afstorage.tf
workload/terraform/greenfield/ADDSscenario/avd.tf
workload/terraform/greenfield/ADDSscenario/data.tf
workload/terraform/greenfield/ADDSscenario/fslogix.tf
workload/terraform/greenfield/ADDSscenario/keyvault.tf
workload/terraform/greenfield/ADDSscenario/network.tf
workload/terraform/greenfield/ADDSscenario/provider.tf
workload/terraform/greenfield/ADDSscenario/terraform.tfvars.sample
workload/terraform/greenfield/ADDSscenario/variables.tf
workload/terraform/modules/insights/main.tf
workload/terraform/modules/network/data.tf
workload/terraform/modules/network/firewallrules/fwpolicy.tf
workload/terraform/modules/network/firewallrules/variables.tf
workload/terraform/modules/network/networking.tf
workload/terraform/modules/network/variables.tf

Update variable name for hub resources
update depreciated log syntax

updates to terraform.

---

carml/1.3.0/Microsoft.Compute/galleries/images/deploy.bicep
workload/arm/deploy-baseline.json
workload/arm/deploy-custom-image.json
workload/bicep/avd-modules/test.bicep
workload/bicep/deploy-custom-image.bicep
workload/bicep/parameters/deploy-custom-image-min-parameters-example.json
workload/bicep/parameters/deploy-custom-image-parameters-example.json
workload/bicep/readme.md

Solving portal deployment of VM from custom image version

Custom image troubleshoot

---

workload/terraform/greenfield/AADscenario/terraform.tfvars.sample
workload/terraform/greenfield/ADDSscenario/terraform.tfvars.sample
workload/terraform/modules/insights/readme.md
workload/terraform/modules/insights/terraform.tfvars.sample
workload/terraform/modules/insights/variables.tf

Create readme for the AVD insights module 
Updated description to variables file
Add sample terraform.tfvars file for deployment

Terraform AVDI update

---

workload/bicep/avd-modules/avd-networking.bicep

Adding default NSG rules and UDR route.

Network security

---

workload/bicep/brownfield/alerts/readme.md

Updated Alerts Brownfield to include PowerShell and Azure CLI deployment instructions

Brownfield Alerts Readme - add PS and AzCLI instructions

---

carml/1.4.0/Compute/virtualMachines/main.bicep
workload/bicep/modules/StorageAzureFiles/deploy.bicep
workload/bicep/modules/avdSessionHosts/.bicep/avdSessionHosts.bicep

NIC Changes to SH and MGMT VM

---

workload/arm/deploy-baseline.json
workload/bicep/modules/avdInsightsMonitoring/deploy.bicep

See notes in commit but this will immediately address the issue of failed deployments when selecting an existing Log Analytics workspace.  Need to eventually review what is configured via the Insights Workbook in comparison to any extra we may be adding or ensure both are consistent if we leave the conditional in place to omit if existing LAW.

J core fix existing law issue363

---

workload/arm/deploy-baseline.json
workload/bicep/modules/avdSessionHosts/.bicep/gpuAzurePolicies.bicep
workload/policies/gpu/policyDefinitions/parameters/policy-definition-es-deploy-amd-gpu-driver.parameters.json
workload/policies/gpu/policyDefinitions/policy-definition-es-deploy-amd-gpu-driver.json
workload/policies/gpu/policyDefinitions/policy-definition-es-deploy-nvidia-gpu-driver.json

custom gpu policies

---

workload/arm/brownfield/deployAlerts.json
workload/bicep/brownfield/alerts/deploy.bicep
workload/bicep/brownfield/alerts/modules/metricsResources.bicep
workload/bicep/brownfield/alerts/updateHistory.md
workload/scripts/alerts/Get-HostPoolInfo.ps1
workload/scripts/alerts/dsHostPoolVMMap.ps1

Removed conditional for deploying alerts for Service Health due to Windows Virtual Desktop category being added to the US Government cloud.  Also updated release notes.

Brownfield - Alerts Update - include SvcHealth for US Gov

---

workload/docs/deploy-baseline.md

Updates to documentation referenced and corrected minor details. Corrected spelling/grammar.

Update guidance on deploy-baseline.md

---

carml/1.3.0/Microsoft.Network/virtualNetworks/deploy.bicep
workload/arm/deploy-baseline.json
workload/arm/deploy-custom-image.json
workload/bicep/modules/networking/deploy.bicep

1. Fix gov deployment network diagnostic issues

Vnet diag gov fix

---

workload/terraform/modules/policies/zerotrust/main.tf
workload/terraform/modules/policies/zerotrust/provider.tf
workload/terraform/modules/policies/zerotrust/readme.md

This PR adds a brownfield module for Terraform AVD Policies for Zero Trust. It deploys a custom policy initiative to set 20 policies for AVD zero trust principles. 
1. main.tf
2. provider.tf
3. readme.md
This PR does introduce new feature and is not a breaking change.
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/avdaccelerator/tree/main)
- [x ] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Docs etc.)

brownfield avd terraform zt policies

---

carml/1.3.0/Microsoft.DesktopVirtualization/hostpools/deploy.bicep
workload/bicep/deploy-baseline.bicep
workload/bicep/modules/avdManagementPlane/deploy.bicep

1. Adding functionality to automatically enable scheduled agent updates on the host pool and add a new scaling plan schedule on Tuesdays to add an additional hour for updates to be applied.

Scheduled agent updates

---

workload/arm/deploy-baseline.json
workload/bicep/deploy-baseline.bicep
workload/bicep/modules/zeroTrust/deploy.bicep
workload/docs/autoGenerated/deploy-baseline.bicep.md

Change on naming of key vault resources.
1. Variable and parameter default value change for KV naming.

Keyvault naming

---

carml/1.3.0/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface.bicep
carml/1.3.0/Microsoft.Compute/virtualMachines/deploy.bicep
carml/1.3.0/Microsoft.DesktopVirtualization/applicationgroups/deploy.bicep
carml/1.3.0/Microsoft.DesktopVirtualization/hostpools/deploy.bicep
carml/1.3.0/Microsoft.DesktopVirtualization/scalingplans/deploy.bicep
carml/1.3.0/Microsoft.DesktopVirtualization/workspaces/deploy.bicep
carml/1.3.0/Microsoft.KeyVault/vaults/deploy.bicep
carml/1.3.0/Microsoft.Network/networkInterfaces/deploy.bicep
carml/1.3.0/Microsoft.Network/networkSecurityGroups/deploy.bicep
carml/1.3.0/Microsoft.Network/publicIPAddresses/deploy.bicep
carml/1.3.0/Microsoft.Network/virtualNetworks/deploy.bicep
carml/1.3.0/Microsoft.Storage/storageAccounts/blobServices/deploy.bicep
carml/1.3.0/Microsoft.Storage/storageAccounts/deploy.bicep
carml/1.3.0/Microsoft.Storage/storageAccounts/fileServices/deploy.bicep
carml/1.3.0/Microsoft.Storage/storageAccounts/queueServices/deploy.bicep
carml/1.3.0/Microsoft.Storage/storageAccounts/tableServices/deploy.bicep
workload/arm/deploy-baseline.json
workload/arm/deploy-custom-image.json
workload/bicep/deploy-baseline.bicep
workload/bicep/modules/avdManagementPlane/deploy.bicep
workload/bicep/modules/avdSessionHosts/deploy.bicep
workload/bicep/modules/networking/deploy.bicep
workload/bicep/modules/storageAzureFiles/deploy.bicep

Remove retention policies from diag settings, this resolve monitoring deployment issues due to API change.

Remove retention policies from diag settings

---

workload/arm/deploy-custom-image.json

Fixed the retention policies in the Custom Image Build JSON file.

Fixed retention policies in Custom Image Build

---

workload/terraform/example/gamedevwm/packer/readme.md

Updates readme.md for more information
1. Adds description. 
2. Adds prereqs
3. Adds usage 
n/a
n/a
- [x ] *(AVD LZA Team Only)* Associated it with relevant [ADO Items](https://dev.azure.com/CSUSolEng/Accelerator%20-%20AVD/_backlogs/backlog/Accelerator%20-%20AVD%20Team/Features)
- [x ] Ensured my code/branch is up-to-date with the …

readme updates

---

.github/ISSUE_TEMPLATE/TF_Issue.yml

This PR is to add feature to create an issue specific to Terraform issues. 
1. Addes Issue page for Terraform issues
1. Not breaking change. Adds new feature
Attached picture shows the change
- [x ] *(AVD LZA Team Only)* Associated it with relevant [ADO Items](https://dev.azure.com/CSUSolEng/Accelerator%20-%20AVD/_backlogs/backlog/Ac …

Terraform update to Issues tab to repo

---

workload/terraform/example/gamedevwm/packer/readme.md
workload/terraform/example/gamedevwm/packer/variables.auto.pkrvars.hcl
workload/terraform/example/gamedevwm/packer/variables.pkr.hcl

Update readme and documentation in code
1. add more details in documentation
N/a
n/a
- [x ] *(AVD LZA Team Only)* Associated it with relevant [ADO Items](https://dev.azure.com/CSUSolEng/Accelerator%20-%20AVD/_backlogs/backlog/Accelerator%20-%20AVD%20Team/Features)
- [x ] Ensured my code/branch is up-to-date with the latest changes …

update to docs

---

workload/terraform/example/gamedevwm/packer/readme.md

Readme update
1. Better documentation
*
N/A
N/A
- x[ ] *(AVD LZA Team Only)* Associated it with relevant [ADO Items](https://dev.azure.com/CSUSolEng/Accelerator%20-%20AVD/_backlogs/backlog/Accelerator%20-%20AVD%20Team/Features)
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` …

Terraform readme updates

---

workload/docs/deploy-baseline.md

keep Azure AD DS instead of Microsoft Entra ID

---

workload/bicep/deploy-baseline.bicep
workload/bicep/modules/avdSessionHosts/.bicep/registerSessionHostsOnHopstPool.bicep
workload/bicep/modules/avdSessionHosts/deploy.bicep
workload/scripts/Set-AvdAgents.ps1

1. Refactoring host pool join and AVD agents install.
1. none

Avd agent install update

---

readme.md
workload/scripts/Monitoring/01_MMA_Report.ps1
workload/scripts/Monitoring/02_MMA_Extention_remove.ps1
workload/scripts/Monitoring/AMA_DCR.ps1
workload/scripts/Monitoring/MMA2AMA.kql
workload/scripts/Monitoring/readme.md

User Story 29289
LZ Automation updates for Monitoring
1. This is just a first draft of migrating host pool vms from MMA to AMA
2. 01_MMA_Report.ps1 Creating report
3. 02_MMA_Extention_remove.ps1  Based on the report remove MMA agent 
Needs to be updated in the future PRs
Can be switch from PowerShell to resource graph query to get the session hosts using MMA?
Have you explored using bicep complete deployment to remove MMA extension and add MMA extension? we are working on MMA code in the ama-update branch ([avdaccelerator/workload/bicep/modules/avdSessionHosts/deploy.bicep at ama-update · Azure/avdaccelerator (github.com)](https://github.com/Azure/avdaccelerator/blob/ama-update/workload/bicep/modules/avdSessionHosts/deploy.bicep)).
Probably you are already working on this, but just in …

first draft

---

workload/terraform/modules/alerts/main.tf
workload/terraform/modules/alerts/variables.tf

1. Fix email address to a variable
*
N/A
- [x ] *(AVD LZA Team Only)* Associated it with relevant [ADO …

alert variable update

---

workload/bicep/deploy-baseline.bicep
workload/docs/autoGenerated/deploy-baseline.bicep.md
workload/docs/deploy-baseline.md
workload/portal-ui/portal-ui-baseline.json

1. Updating "Azure AD Domain Services", service name to "Microsoft Entra Domain Services".

Aadds name update

---

workload/bicep/deploy-baseline.bicep
workload/bicep/modules/avdSessionHosts/.bicep/configureSessionHost.bicep
workload/bicep/modules/avdSessionHosts/deploy.bicep
workload/portal-ui/brownfield/portalUiAddSessionHosts.json
workload/scripts/Set-SessionHostConfiguration.ps1

Issue 536 - Fixing session host config bug
1. Modifying session host configuration powershell script to make domain name and fslogix parameters optional.
2. Modifying session host bicep config to account for non-fslogix deployments.
1. None
- [ x] Read the [Contribution Guide](https://github.com/Azure/avdaccelerator/blob/main/CONTRIBUTING.md) and ensured this PR is compliant with the guide
- [ x] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/avdaccelerator/pulls)
- [ x] Associated it with relevant [GitHub …

Issue 536 - Fixing session host config bug

---

carml/1.3.0/Microsoft.Insights/scheduledQueryRules/deploy.bicep
carml/1.3.0/Microsoft.Insights/scheduledQueryRules/readme.md

1. CARML Microsoft.Insights - add option to pass in Log Alert display name vs just the name which may be truncated and not desired for display purposes.
1. Log Query Rule optional display name and condition to simply use name if it doesn't exist
N/A

JCore-CARML activity log alerts add display name

---

workload/bicep/deploy-baseline.bicep
workload/bicep/deploy-custom-image.bicep
workload/bicep/modules/avdSessionHosts/deploy.bicep
workload/bicep/modules/storageAzureFiles/.bicep/managementVm.bicep
workload/bicep/modules/zeroTrust/.bicep/zeroTrustKeyVault.bicep
workload/bicep/modules/zeroTrust/deploy.bicep

Fixed a few spelling/grammatical errors
Added a key vault purge protection parameter for continuous deployment models and/or testing

Fixed typos and added KV purge protection param

---

workload/docs/getting-started-baseline.md

1. Three  links
- [ x] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [ x] Associated it with relevant [GitHub Issues](https://github.com/Azure/avdaccelerator/issues)
- [x ] *(AVD LZA Team Only)* Associated it with relevant [ADO Items](https://dev.azure.com/CSUSolEng/Accelerator%20-%20AVD/_backlogs/backlog/Accelerator%20-%20AVD%20Team/Features)
- [ x] Ensured my code/branch is up-to-date with the …

Added 3 linked to the whitelist.

---

workload/arm/deploy-baseline.json
workload/bicep/deploy-baseline.bicep
workload/docs/autoGenerated/deploy-baseline.bicep.md
workload/portal-ui/portal-ui-baseline.json

1. Adding option to portal UI so GPU policy deployment can be enabled or not.

Issue-561 fix

---

workload/portal-ui/portal-ui-baseline.json

1. Fixing bugs with domain name text boxes and logic for custom OU path and availability zone settings for storage accounts.
1. None

Baseline portal UI fixes

---

workload/terraform/greenfield/AADDSscenario/readme.md
workload/terraform/greenfield/readme.md

Terraform Entra Domain Services updates

---

readme.md

Added AVD Session Host Replacer. 
Arranged order of the brown field scenario.

Add link to AVD Session Host Replacer

---

workload/workshop/AAD-Hybrid-Lab/README.md
workload/workshop/InstallVSCode.ps1

Changes from Personal to AVD repo link and Entra ID

---

workload/arm/deploy-baseline.json
workload/variables/locations.json

1. Including Italia north region

Including Italia north region

---

workload/arm/brownfield/deployAppAttachToolsVM.json

The ARM template was from a previous version that did not have parameters defined in the updated version from a while back. Thus clicking the Blue button for deployment would fail or show an error that the parameters in the custom UI did not match.
1. Fixes overall deployment as ARM template did not match updated BICEP and Custom UI definition
1. N/A
Tested in lab environment with success.

ARM template update for App Attach VM - Currently BROKEN

---

workload/bicep/modules/avdManagementPlane/deploy.bicep

Update deploy.bicep - Correct swapped application friendlyName

---

workload/bicep/deploy-baseline.bicep
workload/bicep/modules/avdSessionHosts/deploy.bicep
workload/bicep/modules/identity/deploy.bicep

1. Adding logic to fix bug when the deployment doesn't include AVD enterprise app ID.
2. Including the use of managed identity on VMs when deploying using EntraID or enabling monitoring.

Fix for issue 638

---

workload/bicep/modules/avdSessionHosts/deploy.bicep

1. During the AVM migration, an attribute changed. Fixed that attribute to solve this issue.
N/A

fixed managed disk attribute for disk encryption

---

workload/arm/brownfield/deployNewSessionHostsToHostPools.json
workload/bicep/brownfield/newSessionHosts/deploy.bicep

1. Fixing monitoring agent and identity issues on new session host brownfield scenario.

Fix-issue-650

---

avm/1.0.0/res/desktop-virtualization/host-pool/main.bicep
avm/1.0.0/res/desktop-virtualization/workspace/main.bicep
workload/arm/deploy-baseline.json
workload/bicep/deploy-baseline.bicep
workload/bicep/modules/avdInsightsMonitoring/deploy.bicep
workload/bicep/modules/avdManagementPlane/deploy.bicep
workload/bicep/modules/networking/deploy.bicep
workload/docs/getting-started-baseline.md
workload/portal-ui/portal-ui-baseline.json

This adds the capability to deploy AVD Private Link Service.
1. Updates Portal UI to allow the deployment of AVD Private Link and either select an existing Private DNS zone or have it create a new Private DNS zone
2. Adds bicep code to deploy AVD Private Link where the default setting (when enabled) is to only require the session hosts to use AVD Private Link. This keeps all AVD agent traffic in the Azure backbone. This is all configurable with bicep parameters.
1. None
Deployment with existing Private DNS zones:
Deployment with the creation of new Private DNS zones:

Adds AVD Private Link Service

---

workload/workshop/config.model.xml

Create config.model.xml for lab 

---

.gitmodules
workload/bicep/deploy-baseline.bicep
workload/bicep/modules/avdAlerts/deploy.bicep
workload/bicep/modules/avdManagementPlane/deploy.bicep
workload/portal-ui/portal-ui-baseline.json

Added the amba repo as a submodule and then made a module for avd alerts that calls and runs the alerts if user chooses to
1. AMBA sub module 
2. AVDalerts module 
3. Portal UI updates
waiting on small PR for AMBA to fix index issue in one of the alerts
The AMBA PR will fix the last error
- [ x] Read the [Contribution Guide](https://github.com/Azure/avdaccelerator/blob/main/CONTRIBUTING.md) and ensured this PR is compliant with the guide
- [ x] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/avdaccelerator/pulls)
- [ x] Associated it with relevant [GitHub Issues](https://github.com/Azure/avdaccelerator/issues)
- [ x] *(AVD LZA Team Only)* Associated it …

Added AMBA Alerts into AVD accelerator 

---

readme.md
workload/arm/brownfield/deployNewSessionHostsToHostPools.json
workload/arm/deploy-baseline.json
workload/arm/deploy-custom-image.json
workload/bicep/brownfield/newSessionHosts/deploy.bicep
workload/bicep/deploy-baseline.bicep
workload/bicep/deploy-custom-image.bicep
workload/docs/autoGenerated/deploy-baseline.bicep.md.md
workload/docs/autoGenerated/deploy-custom-image.bicep.md
workload/portal-ui/brownfield/portalUiNewSessionHosts.json
workload/portal-ui/portal-ui-baseline.json
workload/portal-ui/portal-ui-custom-image.json
workload/variables/osMarketPlaceImages.json

AVD image update

---

workload/docs/horizonlzaccelerator-nextgen/readme.md

Other grammatical errors fixed and updated wording to be more consistent in the doc.

Updated readme.md with References to Omnissa instead of VMware

---

workload/bicep/brownfield/appAttachToolsVM/Readme.md

Fix PS code for deployment of App Attach Tools VM
1. Fix for issue #674 
1. N/A

Fix PS deploy code for App Attach Tools VM Issue #674

---

workload/arm/deploy-baseline.json
workload/bicep/modules/networking/deploy.bicep
workload/bicep/modules/storageAzureFiles/deploy.bicep

1. Adjusting diagnostic settings for storage and networking
1. None

Adjusting diagnostic settings for storage and networking

---

workload/bicep/brownfield/appAttachToolsVM/Readme.md

Add var to PS and additional Azure CLI code block.
Fix PowerShell deployment and Azure CLI deployment code as it was non-functional. Per Issue #674 
1. PowerShell code in readme for brownfield deployment for App Attach VM revised.
2. Azure CLI code in readme for brownfield deployment for App Attach VM revised.
1. N/A
Deployment tested successfully using either mechanisms.

JCore-Brownfield-AppAttachVM-Fix PS and Azure CLI in readme

---

workload/docs/getting-started-custom-image-build.md

1. Deployment launcher  fix
1. None

deployment launcher fix (issue 695)

---

workload/docs/getting-started-custom-image-build.md

1. Fixing icons from PR 696
1. None

PR 696 fix

---

readme.md

Simple addition of the AVD Client Kiosk Link
1. Link to custom AVD Client Kiosk solution for Windows 10 and 11 IoT thin clients.

Added AVD Client Kiosk as a Brownfield Link

---

readme.md

Added new heading for specialized AVD use case links and added link to hub-and-spoke research enclave project. 
As discussed with @swathibhat1.

Add research enclaves use case

---

workload/arm/deploy-baseline.json
workload/arm/deploy-custom-image.json
workload/bicep/deploy-baseline.bicep
workload/bicep/modules/zeroTrust/.bicep/zeroTrustKeyVault.bicep
workload/bicep/modules/zeroTrust/deploy.bicep

This code update removes the key expiration date for customer-managed keys ensuring idempotency of the deployment. See the referenced issue for more information.
1. [Issue 747](https://github.com/Azure/avdaccelerator/issues/747)
1. None
I ran the same deployment twice using PowerShell and no longer get a conflict on the zero trust key vault (and keys) deployment.
- [] *(AVD LZA Team Only)* Associated it with relevant [ADO Items](https://dev.azure.com/CSUSolEng/Accelerator%20-%20AVD/_backlogs/backlog/Accelerator%20-%20AVD%20Team/Features)

[BugFix] Removed Customer-Managed Keys Key expiration

---

workload/arm/deploy-baseline.json
workload/bicep/modules/avdSessionHosts/.bicep/configureSessionHost.bicep
workload/bicep/modules/avdSessionHosts/deploy.bicep
workload/scripts/Set-SessionHostConfiguration.ps1

Fixes for issues #769

---

workload/portal-ui/brownfield/portalUiNewSessionHosts.json
workload/scripts/Set-SessionHostConfiguration.ps1

Session host configuration update

---

workload/arm/deploy-baseline.json
workload/bicep/deploy-baseline.bicep

Tags updates

---

.github/workflows/tfsec.yml

Update tfsec.yml with top level permission

Update tfsec.yml with top level permission

---

.github/workflows/scorecard.yml

Update scorecard.yml with job level permissions for content & actions

Update scorecard.yml with job level permissions for content & actions

---

.github/workflows/psdocs-mdtogit.yml

Update psdocs-mdtogit.yml with job level permissions

Update psdocs-mdtogit.yml with job level permissions

---

.github/dependabot.yml

This PR enables dependabot version updates for Github-Actions

Create dependabot.yml for version updates

---

.github/workflows/dependency-review.yml

Adding Job level Permission as Read to adhere to SFI and Open SSF Scorecard improvement

Update dependency-review.yml with job level permission as Read

---

workload/arm/deploy-baseline.json
workload/bicep/deploy-baseline.bicep

1. Fix custom image deployment issue
1. None

Baseline: custom image deployment issue

---

workload/arm/deploy-baseline.json
workload/bicep/deploy-baseline.bicep

1. Fixing tagging issue
1. None

Baseline tagging issue fix

---

workload/portal-ui/portal-ui-baseline.json

1. Portal UI custom image fix
1. None

Portal UI custom image fix

---

workload/workshop/AAD-Hybrid-Lab/Templates/adDeploy.json
workload/workshop/AAD-Hybrid-Lab/deploy.json

AD template fix

---

workload/workshop/AAD-Hybrid-Lab/deploy.json

Pip fix - workshop - ADDS

---

avm/1.0.0/res/resources/deployment-script/README.md
avm/1.0.0/res/resources/deployment-script/tests/e2e/cli/main.test.bicep
avm/1.1.0/res/resources/deployment-script/README.md
avm/1.1.0/res/resources/deployment-script/tests/e2e/cli/main.test.bicep

Fix typo in Enviornment to be Environment
1. Fixes trivial typo in echo statements/comments
N/A
N/A
- [X ] Read the [Contribution Guide](https://github.com/Azure/avdaccelerator/blob/main/CONTRIBUTING.md) and ensured this PR is compliant with the guide
- [X ] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [X ] Checked for duplicate [Pull Requests](https://github.com/Azure/avdaccelerator/pulls)
- [X ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/avdaccelerator/tree/main)
- [X ] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Docs etc.)

Patch 2025 09 06 01 fix enviornment typo
